name: Install Script Integration Test
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: none
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get Draft Cli version
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: get_draft_version
        with:
          result-encoding: string
          retries : 3
          script: |
            const tag_url = context.payload.repository.releases_url.replace('{/id}', '/latest');
            const response = await github.request(tag_url);
            return response.data.tag_name;
      - name: Run Install Script
        shell: bash
        run: ./scripts/install.sh
        env:
          DRAFT_CLI_VERSION: ${{ steps.get_draft_version.outputs.result }}
      - name: Validate Command is Installed
        shell: bash
        run: |
          if command -v /home/runner/.local/bin/draft &> /dev/null
          then
              echo "install_dir=/home/runner/.local/bin/draft" >> $GITHUB_ENV
          elif command -v /usr/local/bin/draft &> /dev/null 
          then
            echo "install_dir=/usr/local/bin/draft" >> $GITHUB_ENV
          elif command -v /c/Users/runneradmin/.local/bin/draft &> /dev/null
          then
            echo "install_dir=/c/Users/runneradmin/.local/bin/draft" >> $GITHUB_ENV
          elif command -v /Users/runner/.local/bin/draft &> /dev/null
          then
            echo "install_dir=/Users/runner/.local/bin/draft" >> $GITHUB_ENV
          else 
            echo "draft could not be found"
            exit 1
          fi
      - name: Validate Draft Command Runs
        shell: bash
        run: ${{ env.install_dir }} -h